### ISSUE TITLE
Convert to bazel managed dependencies

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/bazel-go-ethereum#6]
bazel-go-ethereum should attempt to load bazel dependencies, if they are not already present.

This would be a "maybe" type rule where the downstream client would load this library and call 

```python
load("@com_github_ethereum_go_ethereum//:deps.bzl", "go_ethereum_repositories")

go_ethereum_repositories()
```

The `go_ethereum_repositories` rule will load any repository necessary to build go-ethereum which is not already installed. What we are seeing is that there are mixed versions of the same library in our downstream client which leads to wasted/redundant work.

**Comment by prestonvanloon** [comment]
Mostly done in #7

**Comment by nisdas** [comment]
Closing this as its been done as of: https://github.com/prysmaticlabs/bazel-go-ethereum/commit/df74fa9e96217d0fffbe4f25788dd270b25243ed
